---
title: "Datos estadísticas policiales"
author: "Sofía Moya"
date: '2022-06-18'
output:
  html_document:
    code_folding: hide

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lectura carga de paquetes
```{r carga-paquetes, message = FALSE }
library(dplyr)
library(ggplot2)
library(plotly)
library(sf)
library(DT)
library(readxl)
library(readr)
library(leaflet)
library(lubridate)
```

# Lectura datos estadísticas policiales 
```{r lectura-datos, message = FALSE}

estadisticas_policiales <-
  readxl::read_excel("C:/Users/Sofia Moya Bonilla/estadisticaspoliciales2021.xls")

```

# Tabla

```{r tabla, message = FALSE}
estadisticas_policiales %>%
  dplyr::select(Delito, Fecha, Victima, Edad, Genero, Provincia, Canton) %>%
  datatable(
    colnames = c(
      "Delito",
      "Fecha",
      "Víctima",
      "Edad",
      "Género",
      "Provincia",
      "Cánton"
    ),
    options = list(
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    ),
  )


```


# Gráfico 1.Barras simples: Delito por tipo de delito

```{r grafico, message = FALSE}

ggplot2_estadisticas_policiales <-
estadisticas_policiales %>%
  count(Delito) %>%
  ggplot(aes(x = reorder(Delito, n), y = n)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  ggtitle("Cantidad de delitos por tipo de delito") +
  xlab("Delito") +
  ylab("Cantidad") +
  theme_gray() 
ggplotly(ggplot2_estadisticas_policiales) %>% config(locale = 'es')
```


# Gráfico 2.Barras simples: Delitos por mes

```{r, message = FALSE}
informacion <-
  estadisticas_policiales %>%
  mutate(meses = lubridate::month(Fecha))

fechas <-c("Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre")

```

```{r, message = FALSE}
grafico_delitos_meses <-
  informacion %>%
  count(meses) %>%
  ggplot(level = level_order, (aes(x = reorder (fechas, meses), y = n))) +
  geom_bar(stat = "identity") +
  ggtitle("Delitos por mes del año 2021") +
  xlab("Mes") +
  ylab("Número de registros") +
  coord_flip() +
  theme_light()

ggplotly(grafico_delitos_meses)
```

# Grafico 3. Barras apiladas: Delitos por género

```{r}
grafico_barras_delitos_genero <-
  estadisticas_policiales %>%
  ggplot(aes(x = Delito, fill = Genero)) +
  geom_bar(position = "fill") +
  ggtitle("Cantidad de delitos por género") +
  xlab("Delitos") +
  ylab("Cantidad") +
  labs(fill = "Género") +
  coord_flip() +
  theme_classic()

ggplotly(grafico_barras_delitos_genero) 
```

# Gráfico 4. Barras simples. Delitos en cantones.

```{r, message = FALSE}

grafico_barras_simples_cantones <-
estadisticas_policiales %>%
  count(Canton) %>%
  filter(Canton == "SAN JOSE" |
         Canton == "ALAJUELA" |
         Canton == "CARTAGO" |
         Canton == "HEREDIA") %>%
  ggplot(aes(x = reorder(Canton, n), y = n)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  ggtitle("Cantidad de delitos por cantones") +
  xlab("Cantón") +
  ylab("Cantidad") +
  theme_gray() 
ggplotly(grafico_barras_simples_cantones)
```


